# Go to Victorinox.com (or swissarmy.com)
# View all Swiss Army Knives
# Sort by price
# Add to this list all SAKs.
# Exclude: accessories, parts, nail clippers, toys,
# scissors, scale color variations, paracord variations,
# wood variations (though maybe I should note Wood just like Alox)

"victorinox models" = [
    "Classic",
    "Rally",
    "Escort",
    "Bantam",
    "Waiter",
    "Budding Knife",
    "Jetsetter",
    "Walker",
    "Recruit",
    "Pruning Knife",
    "Floral Knife",
    "Nail Clip 582",
    "My First Victorinox",
    "Swiss Army 1 Alox",
    "Wenger",
    "Excelsior",
    "Signature",
    "Tinker Small",
    "Tourist",
    "Classic Alox",
    "Tinker",
    "Spartan",
    "Rambler",
    "Sportsman",
    "Executive 81",
    "Swiss Lite",
    "Bantam Alox",
    "Camper",
    "Hiker",
    "My First Victorinox H",
    "Evolution 10",
    "Climber",
    "Sentinel",
    "Nail Clip 580",
    "Huntsman",
    "Sentinel One Hand",
    "Manager",
    "Super Tinker",
    "Signature Lite",
    "Money Clip Alox",
    "Junior 09",
    "Swiss Card Classic",
    "Swiss Card Nailcare",
    "Evolution Grip 10",
    "Cadet Alox",
    "Alpineer",
    "Fieldmaster",
    "Midnite Manager",
    "Pioneer Alox",
    "Sentinel Clip",
    "Alpineer Grip",
    "Swiss Card Lite",
    "Pruning Knife M",
    "Pruning Knife S",
    "Adventurer",
    "Picknicker",
    "Swiss Army 7 Alox",
    "Fisherman",
    "Evolution Grip 14",
    "Compact",
    "Mini Champ",
    "Ranger Grip 52",
    "Spartan Lite",
    "Mountaineer",
    "Evolution S14",
    "Farmer Alox",
    "Explorer",
    "Pioneer X Alox",
    "Evolution 23",
    "Evolution S17",
    "Evolution Grip 18",
    "Deluxe Tinker",
    "Mini Champ Alox",
    "Cheese Master",
    "Ranger Grip 68",
    "Trailmaster",
    "Ranger",
    "Hunter",
    "Evolution Grip S18",
    "Evolution Grip S17",
    "Ranger Grip 179",
    "Trailmaster",
    "Equestrian",
    "Farmer X Alox",
    "Swiss Soldier's Knife 08",
    "Midnite Mini Champ",
    "Forester",
    "Forester M Grip",
    "Ranger Grip 61",
    "Trailmaster Grip",
    "Ranger Grip 55",
    "Ranger Grip 78",
    "Ranger Grip 79",
    "Outrider",
    "Hunter XT Grip",
    "Ranger Grip 178",
    "Huntsman Lite",
    "Evolution S557",
    "Hunter Pro",
    "Handyman",
    "Evolution Grip S557",
    "Ranger Grip 71 Gardener",
    "Cyber Tool S",
    "Locksmith",
    "Swiss Champ",
    "Rescue Tool",
    "Skipper",
    "Ranger Grip 57 Hunter",
    "Ranger Grip 74",
    "Ranger Grip 58 Hunter",
    "Hercules",
    "Skipper Pro",
    "Hunter Pro Alox",
    "Work Champ",
    "Swiss Tool Spirit X",
    "Swiss Tool X",
    "Cyber Tool L",
    "Outdoor Master Mic S",
    "Swiss Tool",
    "Evolution S54",
    "Cyber Tool Lite",
    "Swiss Tool Spirit X Plus",
    "Evolution Grip S54",
    "Swiss Tool Spirit MX Clip",
    "Swiss Tool Spirit MX",
    "Ranger Grip 174 Handyman",
    "Swiss Tool MX",
    "Wine Master",
    "Swiss Tool X Plus Ratchet",
    "Swiss Tool Spirit X Plus Ratchet",
    "Swiss Tool X Plus",
    "Swiss Tool Spirit MXBS",
    "Swiss Tool Spirit XBS",
    "Swiss Tool MXBS",
    "Ranger Grip Boatsman",
    "Swiss Tool BS",
    "Outdoor Master Mic L",
    "Work Champ XL",
    "Swiss Champ XLT",
    "Swiss Champ XXL",
]
